# Macro file for example B4
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize

# Neutron from 59Cu(d,n) @6 MeV/u
#
/pterp/generator/beam/Z 29
/pterp/generator/beam/A 59
/pterp/generator/beam/energy 590 MeV
/pterp/generator/reaction (d,n)
/pterp/generator/reaction/excitation 5.5 MeV
/pterp/generator/beam/sigma_x 2 mm
/pterp/generator/beam/sigma_y 2 mm
/pterp/generator/beam/sigma_thx 0.1 mrad
/pterp/generator/beam/sigma_thy 0.1 mrad


/run/printProgress 1000
/run/beamOn 10000